### ISSUE TITLE
Read-only without pairing (Home-assistant sensor)

### ISSUE THREAD

**Issue by shafr** [creotiv/MiBand2#18]
Hi! Is it possible to read steps+battery level from Mi Band 2 without pairing 
(just by knowing MAC address ?)

I'm looking into integrating it into Home-assistant infrastructure. 
It would work something like [Mi Flora Sensor](https://www.home-assistant.io/components/sensor.miflora/)
Also it would allow to track presence of person at home using just bracelet.

Thank you.

**Comment by creotiv** [comment]
No.

Kindly yours,
Andrey Nikishaev

Areas         ML/DS/CV/Soft Dev/BizDev/Growth Hacking/Customer Rel/IT
LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Slideshare  https://www.slideshare.net/anikishaev/
Skype         creotiv.in.ua
Mobile        +380632410666
