### ISSUE TITLE
There is a bug while running example.py

### ISSUE THREAD

**Issue by 1807374010** [creotiv/MiBand2#2]
2018-03-25 01:58:29,534 MiBand2 (INFO) > Connecting to F7:DE:36:63:23:E3
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    band = MiBand2(MAC, debug=True)
  File "/root/MiBand2/base.py", line 74, in __init__
    Peripheral.__init__(self, mac_address, addrType=ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 353, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 402, in _connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral F7:DE:36:63:23:E3, addr type: random

Is there any problem with bulepy library or my hci-device? I'm running a Linux in VMware.

**Comment by creotiv** [comment]
That's happen sometimes, its a connectivity problem. Try to restart
bluetooth device and repeat.

**Comment by 1807374010** [comment]
Actually, I'm trying to connect miband2 with my arduino 101. But the miband2 doesn't broadcast any services. While using a phone with nRF connect application, the phone could found two services.So what's wrong with my project? Is the arduino 101 with  BLE4.0 doesn't adopt to the miband2 with BLE4.1?

**Comment by creotiv** [comment]
MiBand2 spec saying that it also using BLE 4.0 http://www.mi.com/en/miband2/
But if you can't connect to the device then there could be hardware limitation, or your hardware using wrong BLE protocol.
But i couldn't say where is the problem, you need to figure out it by yourself.
