### ISSUE TITLE
Past/saved data on the MiBand2

### ISSUE THREAD

**Issue by FHantke** [creotiv/MiBand2#6]
Hello Andrey,

first, thank you for your great article and this program, I learned a lot.

I try to plot past/saved data like minutely steps since yesterday. I know it is possible as I have seen in wireshark, but I don't get it. I don't get it working for me...

Do you have any idea how it could work?

**Comment by creotiv** [comment]
minutes from yesterday = (record_timestamp - yesterday_timestamp) // 60

then just use pandas dataframe to group by minutes and get mean value
df = df.groupby('minutes from yesterday').mean()
df.plot()


Kindly yours,
Andrey Nikishaev

Sit&Fit <https://angel.co/sit-fit/> - underdesk stepper trainer.
Essenly <http://essenly.com> - книги в кратком изложении.
groovyCV <http://groovycv.com> - создание стильных резюме

Rates         Soft Dev from $40/h, Consultation BizDev/Marketing/Customer
Rel/IT from $80/h
LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Slideshare  https://www.slideshare.net/anikishaev/
Skype         creotiv.in.ua
Mobile        +380632410666

**Comment by FHantke** [comment]
Sorry if I phrased this wrong. I mean, I try to extract the past data from the MiBand2 using the BT Gatt Protocol. I saw in the hcilog that the MiFit application sends a timestamp to receive data since this timestamp.

**Comment by Fluel** [comment]
Hi creotiv! nice work. I need to extract past data if it is possible. Can you add this function to the library?  Thanks

**Comment by FHantke** [comment]
Hey, I figured out how it works and will add it as soon as I find time.

**Comment by creotiv** [comment]
Cool) Glad to here this)) will look forward for your update)

**Comment by wshadow** [comment]
Any update on this issue @FHantke ? I would also be very much interested in this feature.

**Comment by FHantke** [comment]
Hello, I finally found the time to add my code to this project.
@creotiv can you give me the permission to push my code?
I will upload a new branch so you can check the changes.

**Comment by creotiv** [comment]
use pull request

Kindly yours,
Andrey Nikishaev

Areas         ML/DS/CV/Soft Dev/BizDev/Growth Hacking/Customer Rel/IT
LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Slideshare  https://www.slideshare.net/anikishaev/
Skype         creotiv.in.ua
Mobile        +380632410666
